# Only repositories on the allow list will be added to the registry.
# The allow list can either contain a string that matches the repository name
# or an organization name with a wildcard (*) as the repository name.
# The comparison will be case-insensitive.
allow:
  # Allow Meroxa and Conduit organizations
  - ConduitIO/*
  - conduitio-labs/*
  - meroxa/*

  # Individual repositories
  - derElektrobesen/conduit-connector-tarantool
  - lovromazgon/conduit-connector-kafka-broker
  - nickchomey/conduit-connector-surrealdb

# The deny list is used to exclude specific repositories from the allow list.
# The deny list takes precedence over the allow list.
# The deny list can either contain a string that matches the repository name
# or an organization name with a wildcard (*) as the repository name.
# The comparison will be case-insensitive.
deny:
  # Deny specific repositories that are allowed in the orgs above
  - ConduitIO/conduit
  - ConduitIO/conduit-connector-template
  - ConduitIO/conduit-operator
  - ConduitIO/conduit-site
  - ConduitIO/streaming-benchmarks
