import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    // 1. Tell me what it is and why this is useful
    {type: 'html', value: '<li class="sidebar-header">What is Conduit</li>'},
    {type: 'autogenerated', dirName: 'what-is-conduit'},
      // Intro
      // Features
    

    // 2. Now, tell me how to use it and what's available
    {type: 'html', value: '<li class="sidebar-header">Using Conduit</li>'},
    {type: 'autogenerated', dirName: 'using-conduit'},
    
      // Installing
      // Getting started
      // Connectors
      // Processors
    

    // 3. Now, tell me how to develop what hasn't been built yet
    {type: 'html', value: '<li class="sidebar-header">Developing Conduit</li>'},
    {type: 'autogenerated', dirName: 'developing-conduit'},
    
    // 5. Now, tell me how to deploy it to production
    {type: 'html', value: '<li class="sidebar-header">Scaling Conduit</li>'},
    {type: 'autogenerated', dirName: 'scaling-conduit'},


    // 6. Now, tell me how to ask for questions
    {type: 'html', value: '<li class="sidebar-header">Community</li>'},
    {type: 'autogenerated', dirName: 'community'},
    // Discord
  
    // 7. What's ahead
    {type: 'html', value: '<li class="sidebar-header">Future of Conduit</li>'},
    {type: 'autogenerated', dirName: 'future-conduit'},
    // roadmap
    // contributing
  ],

  // But you can create a sidebar manually
  
  // docsSidebar: [
  //   'introduction',
  //   'getting-started',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['getting-started/architecture'],
  //   },
  // ],
};

export default sidebars;
