import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    // {type: 'html', value: '<li class="sidebar-header">What is Conduit</li>'},
    // {type: 'html', value: '<li class="sidebar-header">Using Conduit</li>'},
      // {type: 'html', value: '<li class="sidebar-header">What's available</li>'}, // maybe use a different header for processor, connectors, etc
    // {type: 'html', value: '<li class="sidebar-header">Developing Conduit</li>'},
    
    
    {type: 'html', value: '<li class="sidebar-header">Getting started</li>'},
    {type: 'autogenerated', dirName: 'getting-started'},
    {type: 'html', value: '<li class="sidebar-header">Conduit Connectors</li>'},
    {type: 'autogenerated', dirName: 'connectors'},
    {type: 'html', value: '<li class="sidebar-header">Conduit Processors</li>'},
    {type: 'autogenerated', dirName: 'processors'},
    {type: 'html', value: '<li class="sidebar-header">Conduit Pipelines</li>'},
    {type: 'autogenerated', dirName: 'pipelines'},
    {type: 'html', value: '<li class="sidebar-header">Using Conduit</li>'},
    {type: 'autogenerated', dirName: 'using-conduit'},
    {type: 'html', value: '<li class="sidebar-header">Developer guides</li>'},
    {type: 'autogenerated', dirName: 'developer-guides'},
  ],

  // But you can create a sidebar manually
  
  // docsSidebar: [
  //   'introduction',
  //   'getting-started',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['getting-started/architecture'],
  //   },
  // ],
};

export default sidebars;
