name: "Update connectors' list"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  update-connectors-list:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: Update connectors' list
        working-directory: src/connectorgen
        run: |
          go run main.go ${GITHUB_WORKSPACE}/static/connectors.json ${GITHUB_WORKSPACE}/docs/1-using/4-connectors/7-list

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          title: Update connectors' list
          body: Automatic pull request for updating list of connectors
          branch: update-connectors-list
          commit-message: "[automated] Update connectors' list"

      - name: Merge pull request
        run: gh pr merge --auto --squash update-connectors-list
